export const constants = {

    SCHOOL_USER_REGISTER_REQUEST: 'SCHOOL_USER_REGISTER_REQUEST',
    SCHOOL_USER_REGISTER_SUCCESS: 'SCHOOL_USER_REGISTER_SUCCESS',
    SCHOOL_USER_REGISTER_FAILED: 'SCHOOL_USER_REGISTER_FAILED',

    SCHOOL_USER_LOGIN_REQUEST: 'SCHOOL_USER_LOGIN_REQUEST',
    SCHOOL_USER_LOGIN_SUCCESS: 'SCHOOL_USER_LOGIN_SUCCESS',
    SCHOOL_USER_LOGIN_FAILED: 'SCHOOL_USER_LOGIN_FAILED',

}